services:

  auth-service:
    build:
      context: .
      dockerfile: infrastructure/docker/auth.Dockerfile
    ports:
      - "8001"


  cart-service:
    build:
      context: .
      dockerfile: infrastructure/docker/cart.Dockerfile
    ports:
      - "8002"

  notification-service:
    build:
      context: .
      dockerfile: infrastructure/docker/notification.Dockerfile
    ports:
      - "8003"

  order-service:
    build:
      context: .
      dockerfile: infrastructure/docker/order.Dockerfile
    ports:
      - "8004:8004"

    environment:
      ORDER_DATABASE_URL: postgres://postgres:postgres@postgres:5432/order_db

    depends_on:
      postgres:
        condition: service_healthy

  payment-service:
    build:
      context: .
      dockerfile: infrastructure/docker/payment.Dockerfile
    ports:
      - "8005"

  product-service:
    build:
      context: .
      dockerfile: infrastructure/docker/product.Dockerfile
    ports:
      - "8006:8006"

    environment:
      PRODUCT_DATABASE_URL: postgres://postgres:postgres@postgres:5432/product_db

    depends_on:
      postgres:
        condition: service_healthy

  api-gateway:
    build:
      context: .
      dockerfile: infrastructure/docker/gateway.Dockerfile
    ports:
      - "8080:8080"

    environment:
      PRODUCT_SERVICE_URL: http://product-service:8006


  postgres:
    image: postgres:17-alpine
    container_name: ecommerce_postgres
    restart: unless-stopped

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./infrastructure/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres "]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  redis:
    image: redis:alpine
    container_name: ecommerce_redis
    restart: unless-stopped
    ports:
      - "6379:6379"

  nats:
    image: nats:2-alpine
    container_name: ecommerce_nats
    restart: unless-stopped
    ports:
      - "4222:4222"

volumes:
  postgres_data:
